services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
      - 1234:5432
    env_file:
      - back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./back-end
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - back-end/.env
  
  react:
    container_name: react
    build: ./front-end
    volumes:
      - react-volume:/var/www/html

  nginx:
    container_name: nginx_app
    build: ./nginx
    restart: always
    ports:
      - 8080:80
    volumes:
      - react-volume:/var/www/html
    depends_on:
      - db
      - node
      - react

volumes:
  postgres-volume:
  react-volume:
